tap 'homebrew/cask-fonts'
tap 'homebrew/services'
tap 'arbourd/tap'
tap 'fluxcd/tap'
tap 'goreleaser/tap'
tap 'hashicorp/tap'
tap 'kylef/formulae'

brew 'ansifilter'
brew 'bash'
brew 'coreutils'
brew 'fish'
brew 'fluxcd/tap/flux'
brew 'gawk'
brew 'gh'
brew 'git'
brew 'arbourd/tap/git-get'
brew 'arbourd/tap/git-sync'
brew 'gnupg'
brew 'gnu-sed'
brew 'arbourd/tap/go'
brew 'goreleaser/tap/goreleaser'
brew 'grep'
brew 'helm'
brew 'hostess'
brew 'htop'
brew 'iperf3'
brew 'kubeconform'
brew 'kubectl'
brew 'kubectx'
brew 'kustomize'
brew 'make'
brew 'mas'
brew 'mkcert'
brew 'hashicorp/tap/nomad'
brew 'openssl'
brew 'parallel'
brew 'pinentry-mac'
brew 'ripgrep'
brew 'rustup-init'
brew 'shellcheck'
brew 'kylef/formulae/swiftenv'
brew 'swiftlint'
brew 'hashicorp/tap/terraform'
brew 'tflint'
brew 'tfsec'
brew 'tmux'
brew 'arbourd/tap/trash'
brew 'vim'
brew 'watch'
brew 'webtorrent-cli'
brew 'wget'
brew 'yarn'
brew 'yq'
brew 'zstd'

cask '1password'
cask 'appcleaner'
cask 'bettertouchtool'
cask 'discord'
cask 'docker'
cask 'google-chrome'
cask 'iterm2'
cask 'kap'
cask 'logi-options-plus'
cask 'logitune'
cask 'monitorcontrol'
cask 'monodraw'
cask 'ngrok'
cask 'postman'
cask 'signal'
cask 'slack'
cask 'visual-studio-code'
cask 'whatsapp'

cask 'font-source-code-pro'
cask 'font-source-code-pro-for-powerline'

mas '1Password for Safari', id: 1569813296
mas 'AdGuard for Safari', id: 1440147259
mas 'JSON Peep for Safari', id: 1458969831
mas 'Noir', id: 1592917505
mas 'Refined GitHub', id: 1519867270
mas 'Xcode', id: 497799835
