cask_args appdir: '/Applications'

tap 'fisherman/tap'
tap 'homebrew/services'
tap 'homebrew/versions'
tap 'vitorgalvao/tiny-scripts'

brew 'bash'
brew 'doctl'
brew 'fish'
brew 'fisherman/tap/fisherman'
brew 'git-lfs'
brew 'git'
brew 'go'
brew 'gnupg21'
brew 'heroku'
brew 'htop-osx'
brew 'hub'
brew 'keybase'
brew 'kubernetes-cli'
brew 'mas'
brew 'openssl'
brew 'pinentry-mac'
brew 'postgresql'
brew 'pyenv'
brew 'qrencode'
brew 'rbenv'
brew 'ruby-build'
brew 'shellcheck'
brew 'ssh-copy-id'
brew 'tmux'
brew 'trash'
brew 'unrar'
brew 'vim'
brew 'vitorgalvao/tiny-scripts/cask-repair'
brew 'wget'
brew 'xz'
brew 'zbar'

cask 'appcleaner'
cask 'atom'
cask 'bettertouchtool'
cask 'dash'
cask 'docker'
cask 'firefox'
cask 'flux'
cask 'google-chrome'
cask 'Caskroom/versions/google-chrome-canary'
cask 'helm'
cask 'iterm2'
cask 'logitech-gaming-software'
cask 'macvim'
cask 'monodraw'
cask 'postico'
cask 'robomongo'
cask 'viscosity'

mas '1Password', id: 443987910
mas 'Slack', id: 803453959
mas 'Todoist', id: 585829637
