cask_args appdir: '/Applications'

tap 'fisherman/tap'
tap 'homebrew/services'
tap 'homebrew/versions'

brew 'bash'
brew 'docker-clean'
brew 'doctl'
brew 'fish'
brew 'fisherman'
brew 'git-lfs'
brew 'git'
brew 'gnupg21'
brew 'go'
brew 'heroku'
brew 'htop-osx'
brew 'hub'
brew 'kubernetes-cli'
brew 'kubernetes-helm'
brew 'mas'
brew 'mycli'
brew 'openssl'
brew 'pgcli'
brew 'pinentry-mac'
brew 'postgresql'
brew 'pyenv'
brew 'qrencode'
brew 'rancher-cli'
brew 'rbenv'
brew 'ruby-build'
brew 'shellcheck'
brew 'ssh-copy-id'
brew 'the_silver_searcher'
brew 'tmux'
brew 'trash'
brew 'unrar'
brew 'vim'
brew 'wget'
brew 'xz'
brew 'zbar'

cask '1password-beta'
cask 'appcleaner'
cask 'atom'
cask 'bettertouchtool'
cask 'dash'
cask 'docker'
cask 'firefox'
cask 'flux'
cask 'gitter'
cask 'google-chrome'
cask 'google-chrome-canary'
cask 'iterm2'
cask 'keybase'
cask 'logitech-gaming-software'
cask 'macvim'
cask 'monodraw'
cask 'ngrok'
cask 'postico'
cask 'robomongo'
cask 'sequel-pro'
cask 'viscosity'

mas 'Slack', id: 803453959
mas 'Todoist', id: 585829637
