name: ci

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TERM: xterm
  HOMEBREW_NO_AUTO_UPDATE: "1"
  HOMEBREW_NO_REQUIRE_TAP_TRUST: "1"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: sudo apt-get install -y zsh bats
      - run: bats tests/dot.bats

  integration:
    runs-on: macos-latest

    concurrency:
      group: ${{ github.workflow }}-${{ matrix.command }}-${{ github.ref }}
      cancel-in-progress: true

    strategy:
      matrix:
        command:
          - help
          - init
          - update
          - link
          - install-brew
          - install-defaults
          - install-fisher
          - install-vim

    steps:
      - uses: actions/checkout@v7

      - if: ${{ matrix.command == 'install-brew' }}
        run: brew update

      - if: ${{ matrix.command == 'install-brew' }}
        name: Run brew uninstall go
        run: |
          versions=$(brew list | grep -E '^go$|^go@' || true)
          echo $versions

          for v in $versions
          do
            echo "brew uninstall $v"
            brew uninstall $v
          done

      - if: ${{ matrix.command == 'install-brew' }}
        name: Skip installs
        run: |
          # Container and Supacode both require MacOS 26 to install
          echo "HOMEBREW_BUNDLE_BREW_SKIP=container" >> "$GITHUB_ENV"
          echo "HOMEBREW_BUNDLE_CASK_SKIP=supacode" >> "$GITHUB_ENV"

          # MAS installs do not work in CI
          mas_ids=$(cat Brewfile | grep -oE "[0-9]{9,}" | tr '\n' ' ')
          echo $mas_ids
          echo "HOMEBREW_BUNDLE_MAS_SKIP=$mas_ids" >> "$GITHUB_ENV"

      - run: ./dot ${{ matrix.command }}
